#  Dockerfile for Node Express Backend

# Build react client
FROM node:12-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./

RUN npm i --silent

# Copy app source code
COPY . .

# Exports
EXPOSE 5000

CMD ["npm","start"]